server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
    #        server-addr: ${NACOS_ADDR:192.168.0.248:8848} #配置Nacos地址
    #        ip: ${CONSUMER_IP:172.16.180.9}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: discovery
          uri: lb://producer-service
          predicates:
            - Path=/producer/**