server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.248:8848 #配置Nacos地址
    #   ip: 172.16.228.20
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: discovery
          uri: lb://producer-service
          predicates:
            - Path=/producer/**
