apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8080  # 对外暴露的端口
      targetPort: 8080  # 容器内部的端口
  type: LoadBalancer
