server:
  port: 8082

spring:
  application:
    name: consumer-service
#  rabbitmq:java
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest
# 根据ip地址注册
eureka:
  instance:
    ip-address: 172.16.79.29
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
      defaultZone: ${EUREKA_HOSTNAME:http://127.0.0.1:7001/eureka/}
#      defaultZone: http://172.16.223.28:7001/eureka/
#      defaultZone: http://127.0.0.1:7001/eureka/
      instance-id: consumer-service-01

   