server:
  port: 8082

spring:
  application:
    name: consumer-service
#  rabbitmq:java
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
#      defaultZone: ${eureka.instance.hostname:http://127.0.0.1:7001/eureka/}
      defaultZone: http://172.16.197.116:7001/eureka/
#      defaultZone: http://127.0.0.1:7001/eureka/
    instance-id: consumer-service-01

   