server:
  port: 8082

spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
#        server-addr: ${NACOS_ADDR:192.168.0.248:8848} #配置Nacos地址
#        ip: ${CONSUMER_IP:172.16.180.9}
