spring:
  application:
    name: eureka-server
server:
  port: 7001

eureka:
  client:
    #eureka server的地址，所有服务向这个地址中注册
    service-url:
      #      单机配置
      defaultZone: http://127.0.0.1:7001/
    #是否向注册中心注册自己
    register-with-eureka: false
    #声明自己是不是注册中心，是用false，不是用true
    fetch-registry: false
  server:
    #关闭eureka的自我保护机制，eureka自我保护机制：所注册的服务心跳低于阈值后不会立即高线，关闭后会立即高线
    enable-self-preservation: false
  instance:
    hostname: eureka
