server:
  port: 8081

spring:
  application:
    name: producer-service
#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest

eureka:
  instance:
    ip-address: 172.16.90.215
    prefer-ip-address: true
  client:
    service-url:
      #      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
      #      defaultZone: ${eureka.instance.hostname:http://127.0.0.1:7001/eureka/}
#      defaultZone: http://172.16.197.116:7001/eureka/
      defaultZone: http://172.16.223.28:7001/eureka/
#      defaultZone: http://127.0.0.1:7001/eureka/
    instance-id: producer-service-01