server:
  port: 8081

spring:
  application:
    name: producer-service
#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
  instance:
    instance-id: producer-service-01