apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service-deployment
spec:
  replicas: 3  # 部署三个副本
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
        - name: producer-service-container
          image: producer-service:v1
          ports:
            - containerPort: 8081
