apiVersion: v1
kind: Service
metadata:
  name: producer-service-service
spec:
  selector:
    app: producer-service
  ports:
    - protocol: TCP
      port: 8081  # 对外暴露的端口
      targetPort: 8081  # 容器内部的端口
  type: LoadBalancer
